services:
  - type: web
    name: copa-replay-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: copa-replay-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: SHOW_SQL
        value: "false"
      - key: FORMAT_SQL
        value: "false"
      - key: OPENFOOTBALL_BASE_URL
        value: https://raw.githubusercontent.com/openfootball/worldcup.json/master
      - key: WORLDCUP_2026_BASE_URL
        value: https://worldcup26.ir

databases:
  - name: copa-replay-db
    plan: free
    region: oregon
    databaseName: copa_replay
    user: copa_replay
    postgresMajorVersion: "17"
