spring.application.name=copa-replay-api

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/copa_replay}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:dev-secret-change-this}
jwt.expiration=${JWT_EXPIRATION:86400000}

openfootball.base-url=${OPENFOOTBALL_BASE_URL:https://raw.githubusercontent.com/openfootball/worldcup.json/master}

worldcup2026.base-url=${WORLDCUP_2026_BASE_URL:https://worldcup26.ir}
